config/routes.rb
Rails.application.routes.draw do

  root "artists#index"

  resources :artists, only: [:show, :create, :destroy] do
    resources :songs, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy

  validates :name, presence: true
  

  mount_uploader :image, ImageUploader
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def index
    @artists = Artist.all
    @artist = Artist.new

  end

  def show
    @artist = Artist.find(params[:id])
    @song = Song.new
  end

  def create
    @artist = Artist.new(artist_params)
    @artist.save

    redirect_to root_path
  end

  def destroy
    @artist = Artist.find(params[:id])

    @artist.destroy

    redirect_to root_path
  end

private

def artist_params
  params.require(:artist).permit(:name, :image)
end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def create
    @artist = Artist.find(params[:artist_id])

    @song = @artist.songs.build(song_params)

    @song.save

    redirect_to artist_path(@artist)
  end


  def destroy
    @artist = Artist.find(params[:artist_id])

    @song = @artist.songs.find(params[:id])

    @song.destroy

    redirect_to artist_path(@artist)
  end

  private

  def song_params
    params.require(:song).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_artist.html.erb
<%= form_for @artist do |f| %>
  <p><%= f.label "Artist name:" %>
  <%= f.text_field :name %></p>
  <p><%= f.label "Upload image:" %>
    <%= f.file_field :image %></p>
  <%= f.submit :save %>
<% end %>

app/views/artists/index.html.erb
<h1>Artists Overview Page</h1>

<ul>
<% @artists.each do |artist| %>
  <li><p><%= link_to artist.name, artist_path(artist.id) %></p>
  <div><%= image_tag artist.image.thumbnail %></div></li>
<% end %>
</ul>

<%= render 'artist' %>

app/views/artists/show.html.erb
<h1>Artist Show Page</h1>

<h2><%= @artist.name %></h2>
<p><%= image_tag @artist.image.thumbnail %></p>

<ul>
<% @artist.songs.each do |song| %>
  <li><%= song.name %> <%= link_to "[Delete]", artist_song_path(@artist, song), method: :delete, data: { confirm: "Are you sure?" } %></li>
<% end %>
</ul>

<%= render '/songs/song' %>

<hr>

<div><%= link_to "[Back to artist overview page]", root_path %> <%= link_to "[Delete artist]", artist_path(@artist), method: :delete, data: { confirm: "Are you sure?" } %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Newcodaisseurify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/_song.html.erb
<%= form_for [@artist, @song] do |f| %>
  <div><%= f.label "Song title:" %>
  <%= f.text_field :name %>
  <%= f.submit "Add song" %></div>
<% end %>